/// Token accounting.
///
/// Tokens are the unit of cost, of latency and of the context limit, so they
/// are the number an agentic application has to be able to see. A framework
/// that hides usage behind a provider response makes three routine questions
/// unanswerable: what did this conversation cost, which agent in the crew is
/// burning the budget, and are we about to overflow the context window.
///
/// [TokenUsage] is additive, so usage from every model call in a run — across
/// providers, across agents, across retries — sums into one figure.
library;

import 'package:agentic_core/src/common/json_reader.dart';
import 'package:agentic_core/src/common/json_types.dart';
import 'package:meta/meta.dart';

/// Tokens consumed by one or more model calls.
@immutable
final class TokenUsage {
  /// Creates a usage record.
  ///
  /// [totalTokens] is derived from the parts when omitted. It is stored rather
  /// than always computed because some providers report a total that does not
  /// equal the sum — cached and reasoning tokens are counted differently across
  /// vendors — and the provider's own number is the one that gets billed.
  const TokenUsage({
    this.promptTokens = 0,
    this.completionTokens = 0,
    int? totalTokens,
    this.cachedPromptTokens = 0,
    this.reasoningTokens = 0,
  }) : _totalTokens = totalTokens;

  /// Restores usage from JSON.
  factory TokenUsage.fromJson(JsonMap json) => TokenUsage(
    promptTokens: json.intOr('promptTokens', 0),
    completionTokens: json.intOr('completionTokens', 0),
    totalTokens: json.optionalInt('totalTokens'),
    cachedPromptTokens: json.intOr('cachedPromptTokens', 0),
    reasoningTokens: json.intOr('reasoningTokens', 0),
  );

  /// Usage with every counter at zero.
  ///
  /// The identity element for [operator +], and the correct starting value when
  /// accumulating across a run.
  static const TokenUsage empty = TokenUsage();

  /// Tokens in the request, including system prompt, history and tool schemas.
  final int promptTokens;

  /// Tokens generated by the model.
  final int completionTokens;

  /// Prompt tokens served from the provider's cache.
  ///
  /// A subset of [promptTokens], not an addition to it. Cached tokens are
  /// billed at a fraction of the normal rate, so an agent with a large stable
  /// system prompt and many turns can be an order of magnitude cheaper when
  /// caching is working — and this is the field that proves whether it is.
  final int cachedPromptTokens;

  /// Completion tokens spent on internal reasoning rather than on the answer.
  ///
  /// A subset of [completionTokens]. Invisible in the response text but fully
  /// billed, which is why a reasoning model's cost can be many times what the
  /// visible output suggests.
  final int reasoningTokens;

  final int? _totalTokens;

  /// Total tokens billed.
  int get totalTokens => _totalTokens ?? (promptTokens + completionTokens);

  /// Prompt tokens that were not served from cache.
  int get uncachedPromptTokens =>
      (promptTokens - cachedPromptTokens).clamp(0, promptTokens);

  /// Fraction of prompt tokens served from cache, from 0.0 to 1.0.
  ///
  /// Returns 0.0 when there were no prompt tokens, rather than dividing by
  /// zero.
  double get cacheHitRate =>
      promptTokens == 0 ? 0 : cachedPromptTokens / promptTokens;

  /// Whether every counter is zero.
  bool get isEmpty =>
      promptTokens == 0 && completionTokens == 0 && totalTokens == 0;

  /// Adds two usage records field by field.
  ///
  /// ```dart
  /// final runTotal = steps.fold(TokenUsage.empty, (sum, s) => sum + s.usage);
  /// ```
  TokenUsage operator +(TokenUsage other) => TokenUsage(
    promptTokens: promptTokens + other.promptTokens,
    completionTokens: completionTokens + other.completionTokens,
    totalTokens: totalTokens + other.totalTokens,
    cachedPromptTokens: cachedPromptTokens + other.cachedPromptTokens,
    reasoningTokens: reasoningTokens + other.reasoningTokens,
  );

  /// Returns a copy with selected counters replaced.
  TokenUsage copyWith({
    int? promptTokens,
    int? completionTokens,
    int? totalTokens,
    int? cachedPromptTokens,
    int? reasoningTokens,
  }) => TokenUsage(
    promptTokens: promptTokens ?? this.promptTokens,
    completionTokens: completionTokens ?? this.completionTokens,
    totalTokens: totalTokens ?? _totalTokens,
    cachedPromptTokens: cachedPromptTokens ?? this.cachedPromptTokens,
    reasoningTokens: reasoningTokens ?? this.reasoningTokens,
  );

  /// Serialises the usage.
  JsonMap toJson() => pruneNulls(<String, Object?>{
    'promptTokens': promptTokens,
    'completionTokens': completionTokens,
    'totalTokens': totalTokens,
    'cachedPromptTokens': cachedPromptTokens == 0 ? null : cachedPromptTokens,
    'reasoningTokens': reasoningTokens == 0 ? null : reasoningTokens,
  });

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TokenUsage &&
          promptTokens == other.promptTokens &&
          completionTokens == other.completionTokens &&
          totalTokens == other.totalTokens &&
          cachedPromptTokens == other.cachedPromptTokens &&
          reasoningTokens == other.reasoningTokens;

  @override
  int get hashCode => Object.hash(
    promptTokens,
    completionTokens,
    totalTokens,
    cachedPromptTokens,
    reasoningTokens,
  );

  @override
  String toString() {
    final buffer = StringBuffer(
      'TokenUsage(prompt: $promptTokens, completion: $completionTokens, '
      'total: $totalTokens',
    );
    if (cachedPromptTokens > 0) buffer.write(', cached: $cachedPromptTokens');
    if (reasoningTokens > 0) buffer.write(', reasoning: $reasoningTokens');
    buffer.write(')');
    return buffer.toString();
  }
}

/// Summing helpers for collections of usage records.
extension TokenUsageAggregation on Iterable<TokenUsage> {
  /// Adds every record in this collection together.
  TokenUsage sum() => fold(TokenUsage.empty, (total, usage) => total + usage);
}
